ZeroFill equ 0x080008E0
parse_bitmap_list equ 0x08000B30
fptr_300E580 equ 0x080018C2
is_fade_effect_enabled equ 0x080062F8
reset_rendering equ 0x08005F40
reset_IWRAM_struct_unk_8005F6C equ 0x08005F6C
init_2009A8A9_80027C4 equ 0x080027C4
m4a_push_into_index_63h equ 0x08000630
m4a_push_into_list equ 0x0800061E

reset_vram_banks equ 0x080017AA
reset_gfx_related equ 0x0800183C
debug_draw_text equ 0x080049FC
debug_draw_text_init equ 0x80049E0
debug_update_text_render equ 0x8004B28


m4a_choose_track_number equ 0x080005F2
m4a_play_sound_effect equ 0x80005CC


engine_regenerate_rng equ 0x0800151C

engine_set_background_configuration equ 0x080015FC
engine_configure_display_controller equ 0x08001778
engine_reset_display_bg_0123_x_y_offset equ 0x08001788
engine_reset_display_mosaic_size equ 0x080017A0

engine_render_setup_fade_effect_struct equ 0x08006270
engine_setup_gfx_anim_unk equ 0x8002354



; sound engine
engine_m4a_play_track_channel_number equ 0x080005F2
engine_m4a_8000784 equ 0x08000784


reset_20094C0 equ 0x08001AFC
reset_20097A0 equ 0x080023A8
engine_interrupt_handle_and_serial_control_unk equ 0x08145C28
reset_200BC50 equ 0x0813F740
engine_clear_200AD04 equ 0x0803F49C
set_200AD06_to_78h_0 equ 0x0803F4E6

main_title_screen_init_gState_and_timer equ 0x0803E8D4

in_game_world_init_struct_and_unk_1 equ 0x08004DF0
in_game_world_init_struct_and_unk_2 equ 0x08004D48